### PR TITLE
Add support for setting workspace using the config

### LINKED ISSUE #79: Workspace Configuration Not Functioning as Expected
Hi, I'm enjoying using this CLI tool for time tracking during development.

Recently, I started using Toggl with my team, so I need to manage both my personal and team workspaces. However, I noticed that the workspace configuration in the settings doesn't seem to be working as expected.

Here’s the configuration I'm trying to use:

```
# Branch (required)
 # Regex to choose which branch(-es) this block applies to, some examples
 # ['will/.*'] applies to branches like`will/release-workflows`
 # ['^\d+/.*'] applies to branches starting with numbers `123/feat-some-issue`
 # [main] applies only to the branch called `main`
 # ['*'] is the reserved default that applies if no block of higher precedence is present.
 # ['*'] It also applies if current folder is not tracked under source control
 ['*']

 # Workspace (optional, default=null)
 # in this context would resolve to the user's default workspace
 # https://support.toggl.com/en/articles/2452474-introduction-to-workspaces#switching-and-creating-workspaces
 workspace = "team workspace"

 # Description (optional, default="")
 # Accepts any string template with our macros in them
 description = "🔨 {{branch}}"

 # Project (optional, default=No project)
 # Accepts any string template with our macros in them
 project = "{{git_root}}"

 # Task (optional, default=No task)
 # task = "Some task"

 # Tags (optional, default=None)
 tags = ["code"]

 # Billable (optional, default=false)
 billable = true

 # This block will be applied to all branches that match the regex will/.*
 # Branches are matched top-down, so this block will be applied to all branches
 # that match the regex will/.* and no other block will be applied to them.
 # The exception is the default block, which is applied to all branches that
 # don't match any other block.

 # ['will/.*']
```

It appears that the workspace setting only pulls from the user's default workspace, regardless of the custom workspace defined in the config file.

[Reference code line](https://github.com/watercooler-labs/toggl-cli/blob/main/src/commands/start.rs#L106)

Do you have any plans to support custom workspace configurations in the future?

### PR DESCRIPTION
**Pull request by shantanuraj**
## What does this PR do?

- 📥 Use workspace specified in config

If workspace name is specified in the config, we use it while creating a new time-entry.
If the workspace name cannot be matched against the fetched workspaces from the API, we raise an error.
If workspace name is not specified in the config, we use the default workspace.

> Note: At the moment I don't have access to multiple workspaces, it's a paid feature.
> So, I'm unable to test this feature comprehensively. I've tested it with the workspace I have access to.
> Both by specifying the workspace name explicitly in the config and by omitting it.

### Default behaviour (no workspace set)

[asciicast](https://asciinema.org/a/ejJ6Rw0KDnzoj2lBahQwBjdXO)

### Workspace name specified

[asciicast](https://asciinema.org/a/oKoceoKUIsaYHntcyC6AUDzFf)

### Invalid workspace name

[asciicast](https://asciinema.org/a/dXkBEYCCRsXQS91gZNtUmbxX5)

### Gif

kermit-kermit-the-frog

### Context

- Closes #79

### CODE REVIEW

**Comment by junseinagao** [comment]
Hi @shantanuraj,

Thank you for creating the PR!

I tested the build on this branch with a specified workspace configuration. The default behavior (when no workspace is set) and handling of an invalid workspace name both work as expected. However, when a valid workspace name is specified, it appears to record the entry in the default workspace instead.

Here’s a recording of the test for reference:
https://asciinema.org/a/q5bQaiODlWBGa1yaQqcrRyhvF

(In this video, Junsei Nagao’s workspace is not the default workspace.)

**Comment by shantanuraj** [comment]
Good catch, I forgot to update the original line you mentioned in the issue
https://github.com/watercooler-labs/toggl-cli/blob/376ae9d51709f7612eb576c38b3bfab4ee02896e/src/commands/start.rs#L106

I'll make the change as soon as I get the time.

**Comment by shantanuraj** [comment]
Hey @junseinagao I've fixed the issue with workspace_id not being considered
while creating the time-entry.
Was a bit more involved because we started running into rate limit issues
with the Toggl API, so had to restructure the creation code a bit.

**Comment by junseinagao** [comment]
@shantanuraj 

Hi,

I tested the latest development version, and it works perfectly!

However, I did encounter some network errors when creating a time entry in both the current published version and this branch's version. The errors seem to occur less frequently in the latest version of this branch.

Thank you for the fix and all the work you put into resolving the workspace_id issue!

**Comment by shantanuraj** [comment]
Hmm yeah I think it might be related to our (lack of) handling of the 429s.
I'll explore that in another pull-request thanks for testing I'll release this now.

**Pull request merged**
